# Generated by Django 5.1.3 on 2024-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cuisine',
            field=models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('japanese', 'Japanese'), ('thai', 'Thai')], default='No Cuisine', max_length=100),
        ),
    ]
