# Generated by Django 5.1.3 on 2024-12-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('japanese', 'Japanese'), ('thai', 'Thai')], max_length=100),
        ),
    ]
